sudo: false
dist: trusty

language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - hhvm

matrix:
    fast_finish: true
    include:
        - php: 5.6
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
        - php: 7.1
          env: DEPENDENCIES=dev
        - php: 7.0
          env: SYMFONY_VERSION=2.8.* # Test against LTS versions

before_install:
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
    - if [ "$DEPENDENCIES" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;

before_install:
    - composer self-update

install:
    - travis_retry composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction

script:
    - bin/phpunit
